#!/bin/sh
# Clear old stuff
rm -rf [1-9]* constant/polyMesh

# Run the chain
blockMesh > log.blockMesh 2>&1
snappyHexMesh -overwrite > log.snappyHexMesh 2>&1
simpleFoam > log.simpleFoam 2>&1

echo "Simulation complete. Check log.simpleFoam for results."
